### ISSUE TITLE
Your project has been added to a list of copyfree works.

### ISSUE THREAD

**Issue by apotheon** [MerosCrypto/asmr#9]
link: [http://copyfree.org/resources/works#ASMR](http://copyfree.org/resources/works#ASMR)

Please let me know if there are any inaccuracies to be corrected or
improvements to be made in the listing.

**Comment by kayabaNerve** [comment]
Thanks for the heads up. Looks properly filed to me. We do currently support two other currencies if you want to tag to completion (NANO/ZEC), yet simply tagging the core three is also good (and sustainable).
